import type { ReceiptDoc, ReceiptRow } from './receiptRows';

const printDate = () =>
  new Date().toLocaleDateString('en-MY', { day: '2-digit', month: 'short', year: 'numeric' });

const row = (label: string, value: string, cls = '') =>
  `<div class="row${cls}"><span class="lbl">${label}</span><span class="colon">:</span><span class="val">${value}</span></div>`;

export function generateReceiptPdf(doc: ReceiptDoc, extraRows: ReceiptRow[] = []) {
  const allRows = [...doc.rows, ...extraRows];

  // Colons line up in one column, based on the longest label in this receipt
  // (including the fixed Booking Ref / Status rows above the divider).
  const maxLabelLen = Math.max(
    'Booking Ref'.length,
    'Status'.length,
    ...allRows.map(r => r.label.length),
  );

  const rowsHtml = allRows
    .map(r => (r.dividerBefore ? '<hr/>' : '') + row(r.label, r.value, r.emphasis === 'total' ? ' total' : ''))
    .join('');

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"/>
<title>${doc.subtitle} ${doc.bookingRef}</title>
<style>
body{font-family:monospace;font-size:13px;color:#1e293b;width:100%;max-width:680px;margin:0 auto;padding:32px 24px;box-sizing:border-box}
h1{font-size:20px;font-weight:300;margin:0 0 2px}h1 span{color:#ef4444}
.sub{font-size:11px;color:#94a3b8;margin-bottom:24px}
.row{display:flex;align-items:flex-start;margin-bottom:6px}
.lbl{color:#94a3b8;flex:0 0 auto;width:${maxLabelLen}ch}
.colon{color:#94a3b8;flex:0 0 auto;margin-right:6px}
.val{font-weight:700;flex:1;min-width:0}
hr{border:none;border-top:1px dashed #cbd5e1;margin:12px 0}
.total{font-size:16px}
.ref{font-size:10px;color:#94a3b8;text-align:center;margin-top:24px}
@media print{body{margin:0 auto;padding:20px 20px}}
</style></head><body>
<h1>ger<span>a</span>k</h1>
<div class="sub">${doc.subtitle}</div>
${row('Booking Ref', doc.bookingRef)}
${row('Status', doc.statusLabel.toUpperCase())}
<hr/>
${rowsHtml}
<div class="ref">Generated by Gerak · ${printDate()}${doc.createdAt ? ` · ${new Date(doc.createdAt).toLocaleDateString('en-MY', { day: '2-digit', month: 'short', year: 'numeric' })} booked` : ''}</div>
</body></html>`;

  const iframe = document.createElement('iframe');
  iframe.style.cssText = 'position:fixed;width:0;height:0;border:none;opacity:0';
  // srcdoc (set before the iframe is attached) fires exactly one `load`
  // once the receipt HTML itself is parsed — unlike open()/write()/close(),
  // which can fire an earlier `load` for the iframe's initial blank
  // document, and unlike a fixed setTimeout, which is a guess that can
  // both fire too early (blank page printed) or, on some mobile browsers,
  // land far enough outside the tap's gesture window that print() silently
  // no-ops.
  iframe.onload = () => {
    try {
      iframe.contentWindow?.focus();
      iframe.contentWindow?.print();
    } catch (err) {
      console.error('[GERAK] Receipt print failed:', err);
    }
    setTimeout(() => { if (iframe.parentNode) document.body.removeChild(iframe); }, 1000);
  };
  iframe.srcdoc = html;
  document.body.appendChild(iframe);
}
