import { Capacitor } from '@capacitor/core';
import type { ReceiptDoc, ReceiptRow } from './receiptRows';
import { NativePrint } from './nativePrint';

const printDate = () =>
  new Date().toLocaleDateString('en-MY', { day: '2-digit', month: 'short', year: 'numeric' });

// SECURITY [stored XSS]: doc.rows carries fields straight from user-submitted
// booking data (Jubah's fullName/deliveryAddress/matricId, Transport's
// pickup/destination/notes, Rental's notes, etc.) — all free text on
// no-login/guest-facing forms, so any of them can contain literal HTML.
// This string is injected as a REAL DOM document via iframe.srcdoc (not
// React JSX, which would auto-escape), and that iframe has no `sandbox`
// attribute, so it shares the app's own origin — an unescaped
// `<img src=x onerror=...>` in a booking's name would execute with access
// to the parent page's localStorage (where the Supabase session lives) the
// moment any admin/rider opens that booking's receipt. Escaping every
// interpolated value, not just the ones known today to be user-controlled,
// so a future field added to any receipt doesn't silently reopen this.
const escapeHtml = (s: string) =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');

const row = (label: string, value: string, cls = '') =>
  `<div class="row${cls}"><span class="lbl">${escapeHtml(label)}</span><span class="colon">:</span><span class="val">${escapeHtml(value)}</span></div>`;

// Inlined rather than referenced via <img src="/gerak-icon-light.svg"> — this
// prints from an iframe's srcdoc, and print() fires as soon as the HTML
// itself has parsed; an external image load isn't guaranteed to finish
// first; and would leave a blank square in the printed receipt. Inline SVG
// has no separate request to race against.
const LOGO_SVG = `<img src="/gerak-symbol.png" alt="Gerak" style="width:58px;height:auto;display:block"/>`;

function buildReceiptHtml(doc: ReceiptDoc, extraRows: ReceiptRow[] = []): string {
  const allRows = [...doc.rows, ...extraRows];

  // Colons line up in one column, based on the longest label in this receipt
  // (including the fixed Booking Ref / Status / Booking Method rows above
  // the divider — 'Booking Method' is the longest of the three, so leaving
  // it out here when present would misalign every other row's colon).
  const maxLabelLen = Math.max(
    'Booking Ref'.length,
    'Status'.length,
    ...(doc.bookingMethod ? ['Booking Method'.length] : []),
    ...allRows.map(r => r.label.length),
  );

  const rowsHtml = allRows
    .map(r => (r.dividerBefore ? '<hr/>' : '') + row(r.label, r.value, r.emphasis === 'total' ? ' total' : ''))
    .join('');

  return `<!DOCTYPE html><html><head><meta charset="utf-8"/>
<title>${escapeHtml(doc.subtitle)} ${escapeHtml(doc.bookingRef)}</title>
<style>
body{font-family:monospace;font-size:13px;color:#1e293b;width:100%;max-width:680px;margin:0 auto;padding:32px 24px;box-sizing:border-box}
.brand{display:flex;align-items:center;gap:10px;margin-bottom:4px}
.tagline{font-size:10px;color:#94a3b8}
.sub{font-size:11px;color:#94a3b8;margin-bottom:24px}
.row{display:flex;align-items:flex-start;margin-bottom:6px}
.lbl{color:#94a3b8;flex:0 0 auto;width:${maxLabelLen}ch}
.colon{color:#94a3b8;flex:0 0 auto;margin-right:6px}
.val{font-weight:700;flex:1;min-width:0;overflow-wrap:break-word;word-break:break-word}
hr{border:none;border-top:1px dashed #cbd5e1;margin:12px 0}
.total .val{font-size:16px}
.ref{font-size:10px;color:#94a3b8;text-align:center;margin-top:24px}
@media print{body{margin:0 auto;padding:20px 20px}}
</style></head><body>
<div class="brand">${LOGO_SVG}<span class="tagline">Smart Campus Platform</span></div>
<div class="sub">${escapeHtml(doc.subtitle)}</div>
${row('Booking Ref', doc.bookingRef)}
${row('Status', doc.statusLabel.toUpperCase())}
${doc.bookingMethod ? row('Booking Method', doc.bookingMethod.label) : ''}
<hr/>
${rowsHtml}
<div class="ref">Generated by Gerak · ${printDate()}${doc.createdAt ? ` · ${new Date(doc.createdAt).toLocaleDateString('en-MY', { day: '2-digit', month: 'short', year: 'numeric' })} booked` : ''}</div>
</body></html>`;
}

export function generateReceiptPdf(doc: ReceiptDoc, extraRows: ReceiptRow[] = []) {
  const html = buildReceiptHtml(doc, extraRows);

  // Android's WebView doesn't implement window.print() at all (silent
  // no-op) — bridge to a native plugin that hands the same HTML to
  // Android's own PrintManager instead. Web/iOS keep the iframe approach.
  if (Capacitor.getPlatform() === 'android') {
    NativePrint.print({ html, jobName: `${doc.subtitle} ${doc.bookingRef}` })
      .catch(err => console.error('[GERAK] Native print failed:', err));
    return;
  }

  const iframe = document.createElement('iframe');
  iframe.style.cssText = 'position:fixed;width:0;height:0;border:none;opacity:0';
  // srcdoc (set before the iframe is attached) fires exactly one `load`
  // once the receipt HTML itself is parsed — unlike open()/write()/close(),
  // which can fire an earlier `load` for the iframe's initial blank
  // document, and unlike a fixed setTimeout, which is a guess that can
  // both fire too early (blank page printed) or, on some mobile browsers,
  // land far enough outside the tap's gesture window that print() silently
  // no-ops.
  iframe.onload = () => {
    try {
      iframe.contentWindow?.focus();
      iframe.contentWindow?.print();
    } catch (err) {
      console.error('[GERAK] Receipt print failed:', err);
    }
    setTimeout(() => { if (iframe.parentNode) document.body.removeChild(iframe); }, 1000);
  };
  iframe.srcdoc = html;
  document.body.appendChild(iframe);
}
