import type { ReceiptDoc, ReceiptRow } from './receiptRows';

const printDate = () =>
  new Date().toLocaleDateString('en-MY', { day: '2-digit', month: 'short', year: 'numeric' });

const row = (label: string, value: string) =>
  `<div class="row"><span class="lbl">${label} :</span> <span class="val">${value}</span></div>`;

export function generateReceiptPdf(doc: ReceiptDoc, extraRows: ReceiptRow[] = []) {
  const allRows = [...doc.rows, ...extraRows];

  const rowsHtml = allRows
    .map(r => (r.dividerBefore ? '<hr/>' : '') + (r.emphasis === 'total'
      ? `<div class="row total"><span class="lbl">${r.label} :</span> <span class="val">${r.value}</span></div>`
      : row(r.label, r.value)))
    .join('');

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"/>
<title>${doc.subtitle} ${doc.bookingRef}</title>
<style>
body{font-family:monospace;font-size:13px;color:#1e293b;max-width:400px;margin:40px auto;padding:0 20px}
h1{font-size:20px;font-weight:300;margin:0 0 2px}h1 span{color:#ef4444}
.sub{font-size:11px;color:#94a3b8;margin-bottom:24px}
.row{margin-bottom:6px}
.lbl{color:#94a3b8}.val{font-weight:700}
hr{border:none;border-top:1px dashed #cbd5e1;margin:12px 0}
.total{font-size:16px}
.ref{font-size:10px;color:#94a3b8;text-align:center;margin-top:24px}
@media print{body{margin:20px auto}}
</style></head><body>
<h1>ger<span>a</span>k</h1>
<div class="sub">${doc.subtitle}</div>
${row('Booking Ref', doc.bookingRef)}
${row('Status', doc.statusLabel.toUpperCase())}
<hr/>
${rowsHtml}
<div class="ref">Generated by Gerak · ${printDate()}${doc.createdAt ? ` · ${new Date(doc.createdAt).toLocaleDateString('en-MY', { day: '2-digit', month: 'short', year: 'numeric' })} booked` : ''}</div>
</body></html>`;

  const iframe = document.createElement('iframe');
  iframe.style.cssText = 'position:fixed;width:0;height:0;border:none;opacity:0';
  document.body.appendChild(iframe);
  const idoc = iframe.contentDocument ?? iframe.contentWindow?.document;
  if (!idoc) { document.body.removeChild(iframe); return; }
  idoc.open(); idoc.write(html); idoc.close();
  setTimeout(() => {
    iframe.contentWindow?.print();
    setTimeout(() => document.body.removeChild(iframe), 1000);
  }, 300);
}
